<?php

use PHPUnit\Framework\TestCase;
use branix\WhmcsInvoiceRecovery\DocumentValidator;

class DocumentValidatorTest extends TestCase
{
    public function testCleanStripsFormatting(): void
    {
        $this->assertEquals('12345678900', DocumentValidator::clean('123.456.789-00'));
        $this->assertEquals('12345678000123', DocumentValidator::clean('12.345.678/0001-23'));
        $this->assertEquals('1234', DocumentValidator::clean('12a3b4'));
        $this->assertEquals('', DocumentValidator::clean('abc'));
    }

    public function testValidateCpfValid(): void
    {
        // Known valid CPFs (generated by test algorithm)
        $this->assertTrue(DocumentValidator::validateCpf('11144477735'));
        $this->assertTrue(DocumentValidator::validateCpf('111.444.777-35')); // With formatting
    }

    public function testValidateCpfInvalid(): void
    {
        $this->assertFalse(DocumentValidator::validateCpf('00000000000')); // Repeating digits
        $this->assertFalse(DocumentValidator::validateCpf('11111111111'));
        $this->assertFalse(DocumentValidator::validateCpf('12345678900')); // Invalid digit
        $this->assertFalse(DocumentValidator::validateCpf(''));
    }

    public function testValidateCnpjValid(): void
    {
        // Known valid CNPJs
        $this->assertTrue(DocumentValidator::validateCnpj('11222333000181'));
        $this->assertTrue(DocumentValidator::validateCnpj('11.222.333/0001-81')); // With formatting
    }

    public function testValidateCnpjInvalid(): void
    {
        $this->assertFalse(DocumentValidator::validateCnpj('00000000000000')); // Repeating digits
        $this->assertFalse(DocumentValidator::validateCnpj('12345678901234')); // Invalid CNPJ
        $this->assertFalse(DocumentValidator::validateCnpj(''));
    }
}
